server.port : 8888

spring:
  application:
    name: configserver
  bus:
    enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/sys
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 10
  profiles:
    active: jdbc
  cloud:
    config:
      server:
        jdbc:
          order: 1
#          sql: SELECT PROP_KEY, VALUE from PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?
          sql: SELECT PROP_KEY, VALUE from CONFIG_PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?
logging.level.org.springframework.jdbc.core: TRACE
management.endpoints.web.exposure.include: "*"

#  initialization
spring.datasource.initialization-mode: always
spring.datasource.initialize: true
spring.datasource.schema: classpath:/schema.sql
spring.datasource.continue-on-error: true

#application.properties
#POSTGRES
#  spring.datasource.driver-class-name=org.postgresql.Driver
#  spring.datasource.url=jdbc:postgresql://localhost:5432/db-config?useSSL=false
#  spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?useSSL=false
#  spring.datasource.username=postgres
#  spring.datasource.password=postgres

# MYSQL
#  spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#  spring.datasource.url=jdbc:mysql://localhost:3306/sys
#  spring.datasource.username=root
#  spring.datasource.password=macos11!

#common
#  spring.datasource.hikari.connection-timeout=5000
#  spring.datasource.hikari.maximum-pool-size=10
#  spring.cloud.config.server.jdbc.sql=SELECT PROP_KEY, VALUE from PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?
#  spring.jpa.show-sql=true
#  logging.level.org.springframework.jdbc.core = TRACE
#  management.endpoints.web.exposure.include=*
