
DROP TABLE IF EXISTS CONFIG_PROPERTIES;

CREATE TABLE CONFIG_PROPERTIES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  APPLICATION VARCHAR(25) NOT NULL,
  PROFILE VARCHAR(25) NOT NULL,
  LABEL VARCHAR(25) DEFAULT NULL,
  PROP_KEY VARCHAR(25) NOT NULL,
  VALUE VARCHAR(200) NOT NULL
);
